---
# tasks file for apache2
- name: Install Apache2 on Ubuntu
  package:
    name: "{{ item }}" 
    state: present
  with_items:
    - "{{ apache_service }}"
    - php
    - php-mysql
    - php-common

- name: Configuring service 
  service:
    name: "{{ apache_service }}"
    state: started
    #state: restarted
    enabled: yes

- name: Copy index test page
  template:
    src: "templates/index.php.j2"
    dest: "{{ apache_default_site }}/index.php"
  notify: Restart apache2